version: '3'
services:
  app:
    image: composer:latest
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: /bin/bash -c "composer install && composer on"